version: '3.8'

services:
  node-api:
    build: ./api-produtos
    ports:
      - "3001:3001"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: meubanco
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  flask-api:
    build: ./api-pedidos
    ports:
      - "3002:3002"
    depends_on:
      - node-api
      - redis
      - mysql
    environment:
      - PYTHONUNBUFFERED=1

  php-api:
    build: ./api-pagamentos
    ports:
      - "3003:3003"
    depends_on:
      - flask-api

volumes:
  mysql_data:
